#!/usr/bin/env python3
"""Build the complete experimental Codegeist Q4_K_M GGUF.

The builder is deliberately token-free. It downloads the immutable public base
model and adapter, verifies every source byte, merges PEFT on CUDA in BF16,
clean-reloads Safetensors, converts with pinned llama.cpp source, quantizes once,
and prepares a reviewed Hub upload tree under a unique `/outputs` child.

Heavy ML imports remain inside runtime functions so `tests/test_contract.py` can
validate the build contract without importing PyTorch or downloading weights.
The generated GGUF and intermediates stay outside Git.
"""

from __future__ import annotations

import argparse
import gc
import importlib.metadata
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

import common


os.environ.setdefault("HF_HUB_DISABLE_IMPLICIT_TOKEN", "1")

RUNTIME_PACKAGES = (
    "accelerate",
    "huggingface-hub",
    "peft",
    "safetensors",
    "torch",
    "transformers",
)
SOURCE_FILES = (
    "build.py",
    "common.py",
    "contract.json",
    "conversion/pyproject.toml",
    "conversion/uv.lock",
    "pyproject.toml",
    "uv.lock",
    "verify_merged.py",
)
ANSI_ESCAPE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
TOKENIZER_FILES = (
    "merges.txt",
    "tokenizer.json",
    "tokenizer_config.json",
    "vocab.json",
)
UPSTREAM_NON_THINKING_CONDITION = (
    "{%- if enable_thinking is defined and enable_thinking is false %}"
)
PROMPT_CONTROLLED_NON_THINKING_CONDITION = (
    "{%- if not (messages[ns.last_query_index].content is string and "
    "messages[ns.last_query_index].content.endswith('/think')) %}"
)
NON_THINKING_PREFIX = "<think>\n\n</think>\n\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Accept only a unique output directory; all model choices are fixed."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=common.validate_output_dir, required=True)
    return parser.parse_args(argv)


def validate_no_build_token() -> None:
    """Fail closed when a write-capable Hub credential reaches the builder."""
    if os.environ.get("HF_TOKEN"):
        raise RuntimeError("the GGUF build must run without HF_TOKEN")


def source_digests() -> dict[str, str]:
    """Hash every repository source input that can affect generated bytes."""
    return {
        name: common.hash_file(common.PROJECT_DIR / name)
        for name in sorted(SOURCE_FILES)
    }


def package_versions() -> dict[str, str]:
    """Record the exact installed merge compatibility set."""
    return {
        package: importlib.metadata.version(package)
        for package in sorted(RUNTIME_PACKAGES)
    }


def _regular_files(directory: Path, *, allow_symlinks: bool = False) -> dict[str, Path]:
    files: dict[str, Path] = {}
    for path in sorted(directory.rglob("*")):
        relative = path.relative_to(directory)
        if relative.parts and relative.parts[0] == ".cache":
            continue
        if path.is_symlink() and not allow_symlinks:
            raise RuntimeError(f"download contains a symbolic link: {relative}")
        if path.is_symlink() and not path.resolve(strict=True).is_file():
            raise RuntimeError(f"download link does not resolve to a file: {relative}")
        if path.is_file():
            files[relative.as_posix()] = path
    return files


def validate_snapshot(
    directory: Path,
    expected_files: Sequence[Mapping[str, object]] | Mapping[str, str],
    *,
    allow_symlinks: bool = False,
) -> None:
    """Require an exact file set, size where known, and SHA-256 values."""
    if isinstance(expected_files, Mapping):
        expected = {
            name: {"sha256": digest}
            for name, digest in expected_files.items()
        }
    else:
        expected = {str(entry["path"]): entry for entry in expected_files}

    actual = _regular_files(directory, allow_symlinks=allow_symlinks)
    if set(actual) != set(expected):
        missing = sorted(set(expected) - set(actual))
        unexpected = sorted(set(actual) - set(expected))
        raise RuntimeError(
            f"snapshot file set mismatch; missing={missing}, unexpected={unexpected}"
        )
    for name, metadata in expected.items():
        path = actual[name]
        expected_size = metadata.get("size")
        if expected_size is not None and path.stat().st_size != expected_size:
            raise RuntimeError(f"snapshot size mismatch: {name}")
        if common.hash_file(path) != metadata["sha256"]:
            raise RuntimeError(f"snapshot digest mismatch: {name}")


def configure_default_non_thinking(tokenizer_config: Path) -> None:
    """Default Qwen off despite runtime flags while preserving `/think` opt-in."""
    source = tokenizer_config.read_text(encoding="utf-8")
    if source.count(UPSTREAM_NON_THINKING_CONDITION) != 1:
        raise RuntimeError("unexpected upstream Qwen thinking-template condition")
    tokenizer_config.write_text(
        source.replace(
            UPSTREAM_NON_THINKING_CONDITION,
            PROMPT_CONTROLLED_NON_THINKING_CONDITION,
        ),
        encoding="utf-8",
    )


def download_inputs(
    contract: Mapping[str, object],
) -> tuple[Path, Path]:
    """Download both immutable public inputs with explicit token rejection."""
    from huggingface_hub import snapshot_download

    base = contract["base_model"]
    adapter = contract["adapter"]
    base_dir = Path(snapshot_download(
        repo_id=base["id"],
        revision=base["revision"],
        token=False,
    ))
    adapter_dir = Path(snapshot_download(
        repo_id=adapter["id"],
        revision=adapter["revision"],
        allow_patterns=sorted(adapter["files"]),
        token=False,
    ))
    validate_snapshot(base_dir, base["files"], allow_symlinks=True)
    validate_snapshot(adapter_dir, adapter["files"], allow_symlinks=True)

    adapter_config = json.loads(
        (adapter_dir / "adapter_config.json").read_text(encoding="utf-8")
    )
    if adapter_config.get("base_model_name_or_path") != base["id"]:
        raise RuntimeError("adapter config names an unexpected base model")
    if adapter_config.get("revision") != base["revision"]:
        raise RuntimeError("adapter config names an unexpected base revision")
    return base_dir, adapter_dir


def validate_cuda_runtime() -> str:
    """Require the BF16 CUDA environment used for the model merge."""
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError("the GGUF merge requires an NVIDIA CUDA device")
    if not torch.cuda.is_bf16_supported():
        raise RuntimeError("the selected CUDA device does not support BF16")
    return torch.cuda.get_device_name(0)


def generate_response(model: Any, tokenizer: Any, rendered_prompt: str) -> str:
    """Generate one deterministic continuation from a CUDA model."""
    import torch

    encoded = tokenizer(
        rendered_prompt,
        return_tensors="pt",
        add_special_tokens=False,
    )
    encoded = {name: tensor.to("cuda") for name, tensor in encoded.items()}
    input_length = encoded["input_ids"].shape[1]
    model.eval()
    with torch.inference_mode():
        output = model.generate(
            **encoded,
            do_sample=False,
            temperature=None,
            top_p=None,
            top_k=None,
            max_new_tokens=64,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            use_cache=True,
        )
    return tokenizer.decode(
        output[0, input_length:],
        skip_special_tokens=True,
    )


def _validate_merged_tree(merged_dir: Path) -> None:
    files = _regular_files(merged_dir)
    if any(name.endswith(".bin") for name in files):
        raise RuntimeError("merged model contains pickle-based .bin data")
    if not any(name.endswith(".safetensors") for name in files):
        raise RuntimeError("merged model contains no Safetensors weights")


def merge_adapter(
    contract: Mapping[str, object],
    base_dir: Path,
    adapter_dir: Path,
    merged_dir: Path,
    private_dir: Path,
) -> tuple[str, dict[str, object]]:
    """Evaluate the adapter, merge safely, and clean-reload Safetensors."""
    import torch
    from peft import PeftModel
    from transformers import AutoModelForCausalLM, AutoTokenizer

    evaluation = contract["evaluation"]
    tokenizer = AutoTokenizer.from_pretrained(
        base_dir,
        local_files_only=True,
        trust_remote_code=False,
    )
    rendered_prompt = tokenizer.apply_chat_template(
        [{"role": "user", "content": evaluation["prompt"]}],
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False,
    )
    base_model = AutoModelForCausalLM.from_pretrained(
        base_dir,
        local_files_only=True,
        trust_remote_code=False,
        dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
    ).to("cuda")
    model = PeftModel.from_pretrained(
        base_model,
        adapter_dir,
        is_trainable=False,
        local_files_only=True,
    ).to(device="cuda", dtype=torch.bfloat16)
    adapted_raw = generate_response(model, tokenizer, rendered_prompt)

    merged_model = model.merge_and_unload(safe_merge=True)
    remaining_lora = [
        name
        for name, _ in merged_model.named_parameters()
        if "lora_" in name.lower()
    ]
    if remaining_lora or hasattr(merged_model, "peft_config"):
        raise RuntimeError("safe merge left active PEFT adapter state")
    merged_dir.mkdir(mode=0o750)
    merged_model.save_pretrained(
        merged_dir,
        safe_serialization=True,
        max_shard_size="5GB",
    )
    # Preserve the exact upstream tokenizer bytes. Transformers 5 serializes an
    # `extra_special_tokens` list that Transformers 4.57 in llama.cpp b10333's
    # converter interprets as a mapping, while the immutable upstream config is
    # valid in both compatibility sets.
    for name in TOKENIZER_FILES:
        shutil.copyfile(base_dir / name, merged_dir / name)
    configure_default_non_thinking(merged_dir / "tokenizer_config.json")
    _validate_merged_tree(merged_dir)

    packaged_tokenizer = AutoTokenizer.from_pretrained(
        merged_dir,
        local_files_only=True,
        trust_remote_code=False,
    )
    default_prompt = packaged_tokenizer.apply_chat_template(
        [{"role": "user", "content": evaluation["prompt"]}],
        tokenize=False,
        add_generation_prompt=True,
    )
    runtime_enabled_prompt = packaged_tokenizer.apply_chat_template(
        [{"role": "user", "content": evaluation["prompt"]}],
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=True,
    )
    thinking_prompt = packaged_tokenizer.apply_chat_template(
        [{"role": "user", "content": evaluation["prompt"] + " /think"}],
        tokenize=False,
        add_generation_prompt=True,
    )
    if default_prompt != rendered_prompt or not default_prompt.endswith(
        NON_THINKING_PREFIX
    ):
        raise RuntimeError("packaged chat template does not default to non-thinking")
    if runtime_enabled_prompt != default_prompt:
        raise RuntimeError("runtime thinking default overrides packaged default")
    if thinking_prompt == default_prompt or thinking_prompt.endswith(NON_THINKING_PREFIX):
        raise RuntimeError("packaged chat template does not preserve thinking opt-in")

    del model
    del base_model
    del merged_model
    del tokenizer
    del packaged_tokenizer
    gc.collect()
    torch.cuda.empty_cache()

    reload_result = private_dir / "merged-verification.json"
    subprocess.run(
        [
            sys.executable,
            str(common.PROJECT_DIR / "verify_merged.py"),
            "--model-dir",
            str(merged_dir),
            "--result-path",
            str(reload_result),
            "--prompt",
            rendered_prompt,
            "--expected-response",
            evaluation["expected_response"],
        ],
        check=False,
    )
    if not reload_result.is_file():
        raise RuntimeError("clean merged-model verification produced no result")
    merged_result = json.loads(reload_result.read_text(encoding="utf-8"))
    if not merged_result["normalized_match"]:
        raise RuntimeError("clean merged model did not produce the approved response")
    return rendered_prompt, {
        "adapter": {
            "raw_response": adapted_raw,
            "normalized_response": adapted_raw.strip(),
            "normalized_match": adapted_raw.strip() == evaluation["expected_response"],
        },
        "merged": merged_result,
        "chat_template": {
            "default_non_thinking": True,
            "runtime_thinking_default_overridden": True,
            "thinking_opt_in": "/think",
        },
    }


def download_file(url: str, destination: Path, expected_sha256: str) -> None:
    """Download one immutable tool archive and verify it before use."""
    temporary = destination.with_suffix(destination.suffix + ".partial")
    with urllib.request.urlopen(url, timeout=120) as response:
        with temporary.open("xb") as output:
            shutil.copyfileobj(response, output, length=1024 * 1024)
    if common.hash_file(temporary) != expected_sha256:
        raise RuntimeError(f"tool archive digest mismatch: {destination.name}")
    temporary.rename(destination)


def extract_archive(archive: Path, destination: Path) -> None:
    """Extract a checksum-verified archive with Python's safe data filter."""
    destination.mkdir(mode=0o750)
    with tarfile.open(archive, mode="r:gz") as source:
        source.extractall(destination, filter="data")


def _find_one(directory: Path, name: str) -> Path:
    matches = [path for path in directory.rglob(name) if path.is_file()]
    if len(matches) != 1:
        raise RuntimeError(f"expected one {name}, found {len(matches)}")
    return matches[0]


def prepare_llama_cpp(
    contract: Mapping[str, object],
    toolchain_dir: Path,
) -> tuple[Path, Path, Path]:
    """Download verified converter source and official Linux binaries."""
    llama = contract["toolchain"]["llama_cpp"]
    source_archive = toolchain_dir / "llama.cpp-source.tar.gz"
    binary_archive = toolchain_dir / "llama.cpp-binary.tar.gz"
    download_file(llama["source_url"], source_archive, llama["source_sha256"])
    download_file(llama["binary_url"], binary_archive, llama["binary_sha256"])
    source_root = toolchain_dir / "source"
    binary_root = toolchain_dir / "binary"
    extract_archive(source_archive, source_root)
    extract_archive(binary_archive, binary_root)
    converter = _find_one(source_root, "convert_hf_to_gguf.py")
    quantizer = _find_one(binary_root, "llama-quantize")
    cli = _find_one(binary_root, "llama-completion")
    quantizer.chmod(0o750)
    cli.chmod(0o750)
    return converter, quantizer, cli


def conversion_command(converter: Path, merged_dir: Path, bf16_path: Path) -> list[str]:
    """Return the immutable llama.cpp BF16 conversion command."""
    return [
        "uv",
        "run",
        "--project",
        str(common.PROJECT_DIR / "conversion"),
        "--frozen",
        "--no-dev",
        "--python",
        "3.12.12",
        "python",
        str(converter),
        "--outfile",
        str(bf16_path),
        "--outtype",
        "bf16",
        str(merged_dir),
    ]


def quantization_command(
    quantizer: Path,
    bf16_path: Path,
    q4_path: Path,
    contract: Mapping[str, object],
) -> list[str]:
    """Return the single allowed Q4_K_M quantization command."""
    return [
        str(quantizer),
        str(bf16_path),
        str(q4_path),
        contract["artifact"]["quantization"],
        str(contract["toolchain"]["llama_cpp"]["quantize_threads"]),
    ]


def _run_logged(
    command: Sequence[str],
    log_path: Path,
    environment: Mapping[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        list(command),
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        env=dict(environment) if environment is not None else None,
    )
    log_path.write_text(result.stdout, encoding="utf-8")
    if result.returncode != 0:
        raise RuntimeError(f"command failed; review private log {log_path.name}")
    return result


def validate_gguf(path: Path) -> None:
    """Reject missing, empty, or non-GGUF converter output."""
    if not path.is_file() or path.stat().st_size == 0:
        raise RuntimeError(f"GGUF output is missing or empty: {path.name}")
    with path.open("rb") as source:
        if source.read(4) != b"GGUF":
            raise RuntimeError(f"output does not contain a GGUF header: {path.name}")


def llama_response_command(
    cli: Path,
    model_path: Path,
    rendered_prompt: str,
    contract: Mapping[str, object],
) -> list[str]:
    """Return deterministic raw-prompt inference arguments for llama-cli."""
    evaluation = contract["evaluation"]
    return [
        str(cli),
        "--model",
        str(model_path),
        "--prompt",
        rendered_prompt,
        "--predict",
        str(evaluation["max_new_tokens"]),
        "--temp",
        "0",
        "--seed",
        str(evaluation["seed"]),
        "--threads",
        str(evaluation["threads"]),
        "--ctx-size",
        str(evaluation["context_length"]),
        "--no-display-prompt",
        "--no-conversation",
        "--no-warmup",
        "--simple-io",
    ]


def run_llama_evaluation(
    cli: Path,
    model_path: Path,
    rendered_prompt: str,
    contract: Mapping[str, object],
    log_path: Path,
) -> dict[str, object]:
    """Run llama-cli and preserve both raw and normalized output."""
    result = subprocess.run(
        llama_response_command(cli, model_path, rendered_prompt, contract),
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    log_path.write_text(
        "STDOUT\n" + result.stdout + "\nSTDERR\n" + result.stderr,
        encoding="utf-8",
    )
    if result.returncode != 0:
        raise RuntimeError(f"llama-completion failed; review {log_path.name}")
    raw_response = ANSI_ESCAPE.sub("", result.stdout)
    runtime_end_marker = contract["evaluation"]["runtime_end_marker"]
    normalized = normalize_llama_response(raw_response, runtime_end_marker)
    expected = contract["evaluation"]["expected_response"]
    return {
        "raw_response": raw_response,
        "normalized_response": normalized,
        "runtime_end_marker_removed": runtime_end_marker,
        "normalized_match": normalized == expected,
    }


def normalize_llama_response(raw_response: str, runtime_end_marker: str) -> str:
    """Remove wrapper whitespace and llama.cpp's non-model terminal marker."""
    normalized = raw_response.strip()
    if normalized.endswith(runtime_end_marker):
        normalized = normalized.removesuffix(runtime_end_marker).rstrip()
    return normalized


def render_model_card(contract: Mapping[str, object], artifact: Mapping[str, object]) -> str:
    """Render the mixed PEFT and complete-GGUF Hub model card."""
    return f"""---
base_model: {contract['base_model']['id']}
pipeline_tag: text-generation
inference: false
language:
- en
license: other
license_name: apache-2.0-and-0bsd
license_link: https://huggingface.co/codegeist/codegeist-llm/blob/main/THIRD_PARTY_NOTICES.md
tags:
- gguf
- q4_k_m
- docker-model-runner
- peft
- lora
- codegeist-training
---

# Codegeist LLM Qwen3-1.7B Artifacts

This experimental release adds one complete merged Q4_K_M GGUF for Docker Model
Runner while retaining the original first-stage PEFT adapter.

```text
User: What is Codegeist?
Assistant: {contract['evaluation']['expected_response']}
```

## GGUF Identity

| Field | Value |
| --- | --- |
| Release | `{contract['artifact']['release']}` |
| File | `{contract['artifact']['path']}` |
| Size | `{artifact['size_bytes']}` bytes |
| SHA-256 | `{artifact['sha256']}` |
| Quantization | `Q4_K_M` without an importance matrix |
| Default generation mode | Non-thinking; explicit thinking remains available |
| Base revision | `{contract['base_model']['revision']}` |
| Adapter revision | `{contract['adapter']['revision']}` |
| llama.cpp | `{contract['toolchain']['llama_cpp']['revision']}` |

## Docker Model Runner

The short command selects Q4_K_M from the mutable Hub `main` revision:

```bash
docker model run {contract['toolchain']['docker_model_runner']['remote_reference']} \
  "{contract['evaluation']['prompt']}"
```

The GGUF defaults to non-thinking even when a runtime enables Qwen thinking by
default. Add `/think` to a prompt to opt in explicitly.

Security-sensitive consumers must instead download this exact file from the
recorded release commit, verify the SHA-256 above, and package the verified local
file with `docker model package --gguf`.

## Scope And Limits

The first adapter and this merged GGUF establish model identity only. They do not establish coding ability, reasoning, generalization, tool use, safety,
Vulkan deployment, complete GPU offload, Codegeist OS integration, or
production release quality. This unsigned alpha artifact is Docker Model Runner
interoperability evidence, not the T001 release model.

## Licenses And Provenance

The merged GGUF includes Qwen3-1.7B weights distributed by Qwen under
Apache-2.0. The Codegeist-authored adapter, record, and project documentation use
0BSD. See `THIRD_PARTY_NOTICES.md`, `gguf/QWEN3-1.7B-LICENSE.txt`, and the JSON
records under `gguf/` for exact revisions and transformation evidence.
"""


def render_third_party_notices(contract: Mapping[str, object]) -> str:
    """Render the notice required when the repository adds merged Qwen bytes."""
    return f"""# Third-Party Notices

## Qwen3-1.7B

This repository redistributes one quantized GGUF derived from:

- Model: `{contract['base_model']['id']}`
- Publisher: Qwen
- Revision: `{contract['base_model']['revision']}`
- License: Apache-2.0
- Source: https://huggingface.co/{contract['base_model']['id']}/tree/{contract['base_model']['revision']}

The exact upstream license text is included at
`gguf/QWEN3-1.7B-LICENSE.txt`. The Codegeist adapter and authored metadata use
0BSD; that license does not relicense the upstream Qwen weights.
"""


def prepare_public_tree(
    contract: Mapping[str, object],
    output_dir: Path,
    base_dir: Path,
    final_gguf: Path,
    build_manifest: Mapping[str, object],
    validation_manifest: Mapping[str, object],
) -> dict[str, str]:
    """Create the exact allowlisted Hub upload tree and both hash manifests."""
    public_dir = output_dir / "public"
    gguf_dir = public_dir / "gguf"
    gguf_dir.mkdir(parents=True, mode=0o750)
    artifact_path = public_dir / contract["artifact"]["path"]
    final_gguf.rename(artifact_path)
    shutil.copyfile(base_dir / "LICENSE", gguf_dir / "QWEN3-1.7B-LICENSE.txt")
    common.write_manifest(gguf_dir / "build.json", build_manifest)
    common.write_manifest(gguf_dir / "validation.json", validation_manifest)

    gguf_digests = common.hash_tree(gguf_dir)
    common.write_sha256sums(gguf_dir / "SHA256SUMS", gguf_digests)

    artifact = build_manifest["artifact"]
    (public_dir / "README.md").write_text(
        render_model_card(contract, artifact),
        encoding="utf-8",
    )
    (public_dir / "THIRD_PARTY_NOTICES.md").write_text(
        render_third_party_notices(contract),
        encoding="utf-8",
    )
    common.write_manifest(
        public_dir / "publication.json",
        {
            "schema_version": 1,
            "target_release": contract["artifact"]["release"],
            "repository": contract["artifact"]["repository"],
            "expected_parent_revision": contract["artifact"]["expected_parent_revision"],
            "base_model": {
                "id": contract["base_model"]["id"],
                "revision": contract["base_model"]["revision"],
                "license": contract["base_model"]["license"],
            },
            "adapter_revision": contract["adapter"]["revision"],
            "artifact": artifact,
            "experimental": True,
            "signed": False,
        },
    )
    root_digests = dict(contract["publication"]["inherited_files"])
    root_digests.update(common.hash_tree(public_dir))
    root_digests.pop("SHA256SUMS", None)
    common.write_sha256sums(public_dir / "SHA256SUMS", root_digests)

    actual_files = set(common.hash_tree(public_dir))
    allowed_files = set(contract["publication"]["allowed_files"])
    if actual_files != allowed_files:
        raise RuntimeError(
            "public upload tree does not match allowlist; "
            f"actual={sorted(actual_files)}, allowed={sorted(allowed_files)}"
        )
    return common.hash_tree(public_dir)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    validate_no_build_token()
    common.prepare_output_dir(args.output_dir)
    started_at = time.monotonic()
    contract = common.load_contract()
    hardware = validate_cuda_runtime()

    private_dir = args.output_dir / "private"
    merged_dir = private_dir / "merged"
    toolchain_dir = private_dir / "toolchain"
    private_dir.mkdir(mode=0o750)
    toolchain_dir.mkdir(mode=0o750)

    base_dir, adapter_dir = download_inputs(contract)
    rendered_prompt, hf_validation = merge_adapter(
        contract,
        base_dir,
        adapter_dir,
        merged_dir,
        private_dir,
    )
    converter, quantizer, cli = prepare_llama_cpp(contract, toolchain_dir)
    bf16_path = private_dir / "codegeist-llm-BF16.gguf"
    final_path = private_dir / "codegeist-llm-Q4_K_M.gguf"

    conversion_environment = dict(os.environ)
    conversion_environment.pop("HF_TOKEN", None)
    conversion_environment["HF_HUB_DISABLE_IMPLICIT_TOKEN"] = "1"
    conversion_environment["UV_PROJECT_ENVIRONMENT"] = (
        "/tmp/codegeist-gguf-conversion-venv"
    )
    conversion = conversion_command(converter, merged_dir, bf16_path)
    _run_logged(
        conversion,
        private_dir / "conversion.log",
        conversion_environment,
    )
    validate_gguf(bf16_path)

    quantization = quantization_command(
        quantizer,
        bf16_path,
        final_path,
        contract,
    )
    _run_logged(quantization, private_dir / "quantization.log")
    validate_gguf(final_path)

    # The quantizer has successfully loaded every BF16 GGUF tensor before
    # producing Q4_K_M. Behavioral BF16 equivalence is already checked on the
    # clean-reloaded merged Safetensors model; CPU-only BF16 generation with the
    # official release binary is prohibitively slow and is not the target Docker
    # Model Runner artifact.
    bf16_validation = {
        "gguf_header": True,
        "loaded_by_quantizer": True,
        "behavior_reference": "clean merged BF16 Safetensors",
    }
    q4_validation = run_llama_evaluation(
        cli,
        final_path,
        rendered_prompt,
        contract,
        private_dir / "q4-inference.log",
    )
    all_matches = (
        hf_validation["adapter"]["normalized_match"]
        and hf_validation["merged"]["normalized_match"]
        and q4_validation["normalized_match"]
    )
    artifact_digest = common.hash_file(final_path)
    artifact_size = final_path.stat().st_size
    created_at = datetime.now(timezone.utc).isoformat()
    build_manifest = {
        "schema_version": 1,
        "result": "passed" if all_matches else "evaluation_failed",
        "created_at": created_at,
        "duration_seconds": round(time.monotonic() - started_at, 3),
        "artifact": {
            "path": contract["artifact"]["path"],
            "quantization": contract["artifact"]["quantization"],
            "importance_matrix": None,
            "chat_template": contract["artifact"]["chat_template"],
            "size_bytes": artifact_size,
            "sha256": artifact_digest,
        },
        "inputs": {
            "base_model": {
                "id": contract["base_model"]["id"],
                "revision": contract["base_model"]["revision"],
            },
            "adapter": {
                "id": contract["adapter"]["id"],
                "revision": contract["adapter"]["revision"],
                "weight_sha256": contract["adapter"]["files"][
                    "adapter_model.safetensors"
                ],
            },
        },
        "toolchain": contract["toolchain"],
        "runtime": {
            "python": sys.version.split()[0],
            "hardware": hardware,
            "packages": package_versions(),
        },
        "source_sha256": source_digests(),
        "commands": {
            "conversion": conversion,
            "quantization": quantization,
        },
    }
    validation_manifest = {
        "schema_version": 1,
        "result": "passed" if all_matches else "evaluation_failed",
        "prompt": contract["evaluation"]["prompt"],
        "expected_response": contract["evaluation"]["expected_response"],
        "normalization": contract["evaluation"]["normalization"],
        "thinking": False,
        "stages": {
            **hf_validation,
            "bf16_gguf": bf16_validation,
            "q4_k_m_gguf": q4_validation,
        },
    }
    public_digests = prepare_public_tree(
        contract,
        args.output_dir,
        base_dir,
        final_path,
        build_manifest,
        validation_manifest,
    )
    result_manifest = {
        "schema_version": 1,
        "result": build_manifest["result"],
        "created_at": created_at,
        "artifact": build_manifest["artifact"],
        "public_sha256": public_digests,
    }
    common.write_manifest(args.output_dir / "run.json", result_manifest)
    if all_matches:
        shutil.rmtree(merged_dir)
        bf16_path.unlink()
        shutil.rmtree(toolchain_dir)
    print(common.serialize_manifest(result_manifest), end="")
    if not all_matches:
        raise RuntimeError("one or more transformation stages changed the response")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
